# Config for EleutherEvalRecipe in eleuther_eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune run eleuther_eval --config eleuther_evaluation tasks=["truthfulqa_mc2","hellaswag"]

# Model Arguments
model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: ./checkpoints/Llama-3-KoBLLa-Instruct/
  checkpoint_files: [
    meta_model_init.pt
  ]
  recipe_checkpoint: null
  output_dir: ./checkpoints/Llama-3-KoBLLa-Instruct/
  model_type: LLAMA3

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ./checkpoints/Meta-Llama-3-8B-Instruct/original/tokenizer.model

# Environment
device: cuda
dtype: bf16
seed: 2024

# EleutherAI specific eval args
tasks: ["truthfulqa_mc2"]
limit: null
max_seq_length: 4096

# Quantization specific args
quantizer: null
